"""Seed pipeline for verified food reference database.
Contains 105 curated Indian and international nutritional food staples adhering to
ICMR-NIN 2024 and USDA reference standards.
"""
import asyncio
import json
import uuid
from decimal import Decimal
from typing import List, Dict, Any
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker

from backend.src.models.food import VerifiedFoodReference

FOOD_SEED_ITEMS: List[Dict[str, Any]] = [
    # 1. Grains & Breads (15 items)
    {
        "food_name": "Roti / Chapati (Whole Wheat)",
        "regional_name": "Phulka / Roti",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("264.00"),
        "protein_per_100g": Decimal("9.00"),
        "carbs_per_100g": Decimal("51.00"),
        "fat_per_100g": Decimal("2.50"),
        "fiber_per_100g": Decimal("7.00"),
        "sodium_per_100g": Decimal("150.00"),
        "sugar_per_100g": Decimal("1.00"),
        "portion_sizes_json": [
            {"unit": "1 medium roti", "weight_g": 35.0},
            {"unit": "2 medium rotis", "weight_g": 70.0},
            {"unit": "100g serving", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Paratha (Plain Tawa)",
        "regional_name": "Plain Paratha",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("310.00"),
        "protein_per_100g": Decimal("7.50"),
        "carbs_per_100g": Decimal("45.00"),
        "fat_per_100g": Decimal("11.00"),
        "fiber_per_100g": Decimal("5.00"),
        "sodium_per_100g": Decimal("220.00"),
        "sugar_per_100g": Decimal("1.00"),
        "portion_sizes_json": [
            {"unit": "1 plain paratha", "weight_g": 60.0},
            {"unit": "100g serving", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Naan (Tandoori Plain)",
        "regional_name": "Tandoori Naan",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("290.00"),
        "protein_per_100g": Decimal("8.50"),
        "carbs_per_100g": Decimal("52.00"),
        "fat_per_100g": Decimal("5.00"),
        "fiber_per_100g": Decimal("2.50"),
        "sodium_per_100g": Decimal("380.00"),
        "sugar_per_100g": Decimal("2.00"),
        "portion_sizes_json": [
            {"unit": "1 naan", "weight_g": 90.0},
            {"unit": "100g serving", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Brown Rice (Cooked)",
        "regional_name": "Bhura Chawal",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("123.00"),
        "protein_per_100g": Decimal("2.70"),
        "carbs_per_100g": Decimal("25.60"),
        "fat_per_100g": Decimal("1.00"),
        "fiber_per_100g": Decimal("1.80"),
        "sodium_per_100g": Decimal("4.00"),
        "sugar_per_100g": Decimal("0.40"),
        "portion_sizes_json": [
            {"unit": "1 katori cooked", "weight_g": 150.0},
            {"unit": "1 cup cooked", "weight_g": 195.0},
        ],
    },
    {
        "food_name": "Basmati White Rice (Cooked)",
        "regional_name": "Chawal / Bhat",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("130.00"),
        "protein_per_100g": Decimal("2.70"),
        "carbs_per_100g": Decimal("28.20"),
        "fat_per_100g": Decimal("0.30"),
        "fiber_per_100g": Decimal("0.40"),
        "sodium_per_100g": Decimal("2.00"),
        "sugar_per_100g": Decimal("0.10"),
        "portion_sizes_json": [
            {"unit": "1 katori cooked", "weight_g": 150.0},
            {"unit": "1 plate cooked", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Poha (Cooked Flattened Rice)",
        "regional_name": "Kanda Poha",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("180.00"),
        "protein_per_100g": Decimal("3.20"),
        "carbs_per_100g": Decimal("33.00"),
        "fat_per_100g": Decimal("3.80"),
        "fiber_per_100g": Decimal("2.00"),
        "sodium_per_100g": Decimal("210.00"),
        "sugar_per_100g": Decimal("1.50"),
        "portion_sizes_json": [
            {"unit": "1 bowl", "weight_g": 180.0},
            {"unit": "100g serving", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Upma (Cooked Semolina)",
        "regional_name": "Rava Upma",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("165.00"),
        "protein_per_100g": Decimal("3.50"),
        "carbs_per_100g": Decimal("26.00"),
        "fat_per_100g": Decimal("5.00"),
        "fiber_per_100g": Decimal("2.00"),
        "sodium_per_100g": Decimal("250.00"),
        "sugar_per_100g": Decimal("1.00"),
        "portion_sizes_json": [
            {"unit": "1 bowl", "weight_g": 180.0},
            {"unit": "100g serving", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Idli (Steamed Rice-Dal Cake)",
        "regional_name": "Idli",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("140.00"),
        "protein_per_100g": Decimal("4.50"),
        "carbs_per_100g": Decimal("28.00"),
        "fat_per_100g": Decimal("0.80"),
        "fiber_per_100g": Decimal("1.80"),
        "sodium_per_100g": Decimal("180.00"),
        "sugar_per_100g": Decimal("0.50"),
        "portion_sizes_json": [
            {"unit": "1 piece", "weight_g": 40.0},
            {"unit": "2 pieces", "weight_g": 80.0},
        ],
    },
    {
        "food_name": "Plain Dosa",
        "regional_name": "Sada Dosa",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("168.00"),
        "protein_per_100g": Decimal("3.90"),
        "carbs_per_100g": Decimal("28.50"),
        "fat_per_100g": Decimal("4.20"),
        "fiber_per_100g": Decimal("1.50"),
        "sodium_per_100g": Decimal("220.00"),
        "sugar_per_100g": Decimal("0.80"),
        "portion_sizes_json": [
            {"unit": "1 medium dosa", "weight_g": 90.0},
            {"unit": "100g serving", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Masala Dosa",
        "regional_name": "Masala Dosa",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("215.00"),
        "protein_per_100g": Decimal("4.20"),
        "carbs_per_100g": Decimal("32.00"),
        "fat_per_100g": Decimal("7.80"),
        "fiber_per_100g": Decimal("2.50"),
        "sodium_per_100g": Decimal("310.00"),
        "sugar_per_100g": Decimal("1.20"),
        "portion_sizes_json": [
            {"unit": "1 full dosa", "weight_g": 160.0},
        ],
    },
    {
        "food_name": "Rolled Oats (Cooked with Water)",
        "regional_name": "Oatmeal",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("71.00"),
        "protein_per_100g": Decimal("2.50"),
        "carbs_per_100g": Decimal("12.00"),
        "fat_per_100g": Decimal("1.40"),
        "fiber_per_100g": Decimal("1.70"),
        "sodium_per_100g": Decimal("2.00"),
        "sugar_per_100g": Decimal("0.30"),
        "portion_sizes_json": [
            {"unit": "1 bowl cooked", "weight_g": 200.0},
            {"unit": "100g serving", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Quinoa (Cooked)",
        "regional_name": "Quinoa",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("120.00"),
        "protein_per_100g": Decimal("4.40"),
        "carbs_per_100g": Decimal("21.30"),
        "fat_per_100g": Decimal("1.90"),
        "fiber_per_100g": Decimal("2.80"),
        "sodium_per_100g": Decimal("7.00"),
        "sugar_per_100g": Decimal("0.90"),
        "portion_sizes_json": [
            {"unit": "1 cup cooked", "weight_g": 185.0},
        ],
    },
    {
        "food_name": "Dalia / Broken Wheat Khichdi",
        "regional_name": "Daliya",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("110.00"),
        "protein_per_100g": Decimal("3.40"),
        "carbs_per_100g": Decimal("20.00"),
        "fat_per_100g": Decimal("1.80"),
        "fiber_per_100g": Decimal("3.50"),
        "sodium_per_100g": Decimal("180.00"),
        "sugar_per_100g": Decimal("0.50"),
        "portion_sizes_json": [
            {"unit": "1 bowl", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Whole Wheat Bread",
        "regional_name": "Brown Bread",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("247.00"),
        "protein_per_100g": Decimal("11.00"),
        "carbs_per_100g": Decimal("43.00"),
        "fat_per_100g": Decimal("3.40"),
        "fiber_per_100g": Decimal("6.00"),
        "sodium_per_100g": Decimal("450.00"),
        "sugar_per_100g": Decimal("4.50"),
        "portion_sizes_json": [
            {"unit": "1 slice", "weight_g": 35.0},
            {"unit": "2 slices", "weight_g": 70.0},
        ],
    },
    {
        "food_name": "Pav (Indian Dinner Roll)",
        "regional_name": "Ladi Pav",
        "category": "grains_cereals",
        "calories_per_100g": Decimal("275.00"),
        "protein_per_100g": Decimal("8.50"),
        "carbs_per_100g": Decimal("53.00"),
        "fat_per_100g": Decimal("2.80"),
        "fiber_per_100g": Decimal("2.00"),
        "sodium_per_100g": Decimal("420.00"),
        "sugar_per_100g": Decimal("3.00"),
        "portion_sizes_json": [
            {"unit": "1 piece", "weight_g": 45.0},
            {"unit": "2 pieces", "weight_g": 90.0},
        ],
    },

    # 2. Lentils & Legumes (12 items)
    {
        "food_name": "Yellow Dal Tadka",
        "regional_name": "Toor / Moong Dal",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("115.00"),
        "protein_per_100g": Decimal("6.20"),
        "carbs_per_100g": Decimal("15.00"),
        "fat_per_100g": Decimal("3.40"),
        "fiber_per_100g": Decimal("4.00"),
        "sodium_per_100g": Decimal("240.00"),
        "sugar_per_100g": Decimal("0.80"),
        "portion_sizes_json": [
            {"unit": "1 katori cooked", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Moong Dal Khichdi",
        "regional_name": "Khichdi",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("135.00"),
        "protein_per_100g": Decimal("5.00"),
        "carbs_per_100g": Decimal("22.00"),
        "fat_per_100g": Decimal("3.00"),
        "fiber_per_100g": Decimal("3.00"),
        "sodium_per_100g": Decimal("210.00"),
        "sugar_per_100g": Decimal("0.50"),
        "portion_sizes_json": [
            {"unit": "1 bowl cooked", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Chana Dal Curry",
        "regional_name": "Bengal Gram Dal",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("130.00"),
        "protein_per_100g": Decimal("7.00"),
        "carbs_per_100g": Decimal("17.50"),
        "fat_per_100g": Decimal("3.40"),
        "fiber_per_100g": Decimal("5.00"),
        "sodium_per_100g": Decimal("250.00"),
        "sugar_per_100g": Decimal("1.00"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Rajma Curry (Kidney Beans)",
        "regional_name": "Rajma Masala",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("140.00"),
        "protein_per_100g": Decimal("6.80"),
        "carbs_per_100g": Decimal("20.00"),
        "fat_per_100g": Decimal("3.60"),
        "fiber_per_100g": Decimal("5.50"),
        "sodium_per_100g": Decimal("260.00"),
        "sugar_per_100g": Decimal("1.20"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
            {"unit": "1 bowl", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Chole Masala (Chickpeas)",
        "regional_name": "Kabuli Chana",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("165.00"),
        "protein_per_100g": Decimal("7.20"),
        "carbs_per_100g": Decimal("21.00"),
        "fat_per_100g": Decimal("5.80"),
        "fiber_per_100g": Decimal("5.20"),
        "sodium_per_100g": Decimal("290.00"),
        "sugar_per_100g": Decimal("1.50"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Masoor Dal (Red Lentil)",
        "regional_name": "Lal Masoor",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("110.00"),
        "protein_per_100g": Decimal("6.50"),
        "carbs_per_100g": Decimal("14.50"),
        "fat_per_100g": Decimal("2.80"),
        "fiber_per_100g": Decimal("3.80"),
        "sodium_per_100g": Decimal("220.00"),
        "sugar_per_100g": Decimal("0.70"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Sambar",
        "regional_name": "South Indian Sambar",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("85.00"),
        "protein_per_100g": Decimal("3.80"),
        "carbs_per_100g": Decimal("13.00"),
        "fat_per_100g": Decimal("2.00"),
        "fiber_per_100g": Decimal("3.20"),
        "sodium_per_100g": Decimal("280.00"),
        "sugar_per_100g": Decimal("1.80"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
            {"unit": "1 bowl", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Dal Makhani",
        "regional_name": "Maa ki Dal",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("168.00"),
        "protein_per_100g": Decimal("5.50"),
        "carbs_per_100g": Decimal("16.50"),
        "fat_per_100g": Decimal("9.00"),
        "fiber_per_100g": Decimal("4.20"),
        "sodium_per_100g": Decimal("280.00"),
        "sugar_per_100g": Decimal("1.20"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Boiled Chickpeas",
        "regional_name": "Boiled Chana",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("164.00"),
        "protein_per_100g": Decimal("8.90"),
        "carbs_per_100g": Decimal("27.40"),
        "fat_per_100g": Decimal("2.60"),
        "fiber_per_100g": Decimal("7.60"),
        "sodium_per_100g": Decimal("24.00"),
        "sugar_per_100g": Decimal("4.80"),
        "portion_sizes_json": [
            {"unit": "1 cup", "weight_g": 164.0},
            {"unit": "100g serving", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Sprouted Moong (Raw)",
        "regional_name": "Ankurit Moong",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("105.00"),
        "protein_per_100g": Decimal("7.00"),
        "carbs_per_100g": Decimal("19.00"),
        "fat_per_100g": Decimal("0.40"),
        "fiber_per_100g": Decimal("3.50"),
        "sodium_per_100g": Decimal("15.00"),
        "sugar_per_100g": Decimal("2.00"),
        "portion_sizes_json": [
            {"unit": "1 bowl", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Soya Chunks (Boiled)",
        "regional_name": "Meal Maker",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("120.00"),
        "protein_per_100g": Decimal("17.00"),
        "carbs_per_100g": Decimal("9.00"),
        "fat_per_100g": Decimal("0.50"),
        "fiber_per_100g": Decimal("5.00"),
        "sodium_per_100g": Decimal("10.00"),
        "sugar_per_100g": Decimal("1.00"),
        "portion_sizes_json": [
            {"unit": "1 bowl cooked", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Lobia Curry (Black Eyed Peas)",
        "regional_name": "Chawli / Lobia",
        "category": "lentils_legumes",
        "calories_per_100g": Decimal("125.00"),
        "protein_per_100g": Decimal("6.50"),
        "carbs_per_100g": Decimal("17.00"),
        "fat_per_100g": Decimal("3.20"),
        "fiber_per_100g": Decimal("4.50"),
        "sodium_per_100g": Decimal("230.00"),
        "sugar_per_100g": Decimal("1.00"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },

    # 3. Dairy & Alternatives (12 items)
    {
        "food_name": "Cow Milk (Whole 3.5% Fat)",
        "regional_name": "Gay ka Doodh",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("64.00"),
        "protein_per_100g": Decimal("3.30"),
        "carbs_per_100g": Decimal("4.80"),
        "fat_per_100g": Decimal("3.50"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("45.00"),
        "sugar_per_100g": Decimal("4.80"),
        "portion_sizes_json": [
            {"unit": "1 glass", "weight_g": 200.0},
            {"unit": "1 cup", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Buffalo Milk (Full Cream)",
        "regional_name": "Bhains ka Doodh",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("97.00"),
        "protein_per_100g": Decimal("3.80"),
        "carbs_per_100g": Decimal("5.20"),
        "fat_per_100g": Decimal("6.90"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("50.00"),
        "sugar_per_100g": Decimal("5.20"),
        "portion_sizes_json": [
            {"unit": "1 glass", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Curd / Plain Dahi (Whole Milk)",
        "regional_name": "Dahi / Yogurt",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("61.00"),
        "protein_per_100g": Decimal("3.50"),
        "carbs_per_100g": Decimal("4.70"),
        "fat_per_100g": Decimal("3.30"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("46.00"),
        "sugar_per_100g": Decimal("4.70"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 120.0},
            {"unit": "1 cup", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Greek Yogurt (Plain Non-fat)",
        "regional_name": "Greek Dahi",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("59.00"),
        "protein_per_100g": Decimal("10.20"),
        "carbs_per_100g": Decimal("3.60"),
        "fat_per_100g": Decimal("0.40"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("36.00"),
        "sugar_per_100g": Decimal("3.20"),
        "portion_sizes_json": [
            {"unit": "1 cup", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Paneer (Indian Cottage Cheese)",
        "regional_name": "Paneer",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("265.00"),
        "protein_per_100g": Decimal("18.30"),
        "carbs_per_100g": Decimal("3.40"),
        "fat_per_100g": Decimal("20.00"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("22.00"),
        "sugar_per_100g": Decimal("2.50"),
        "portion_sizes_json": [
            {"unit": "50g cubes", "weight_g": 50.0},
            {"unit": "100g slab", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Tofu (Firm)",
        "regional_name": "Soy Paneer",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("83.00"),
        "protein_per_100g": Decimal("10.00"),
        "carbs_per_100g": Decimal("1.90"),
        "fat_per_100g": Decimal("4.50"),
        "fiber_per_100g": Decimal("0.90"),
        "sodium_per_100g": Decimal("12.00"),
        "sugar_per_100g": Decimal("0.50"),
        "portion_sizes_json": [
            {"unit": "100g slab", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Chaas / Buttermilk (Spiced)",
        "regional_name": "Chaas / Mattha",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("28.00"),
        "protein_per_100g": Decimal("1.60"),
        "carbs_per_100g": Decimal("2.40"),
        "fat_per_100g": Decimal("1.30"),
        "fiber_per_100g": Decimal("0.20"),
        "sodium_per_100g": Decimal("160.00"),
        "sugar_per_100g": Decimal("2.40"),
        "portion_sizes_json": [
            {"unit": "1 glass", "weight_g": 250.0},
        ],
    },
    {
        "food_name": "Desi Ghee (Clarified Butter)",
        "regional_name": "Shuddh Desi Ghee",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("884.00"),
        "protein_per_100g": Decimal("0.30"),
        "carbs_per_100g": Decimal("0.00"),
        "fat_per_100g": Decimal("98.00"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("2.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "1 tsp", "weight_g": 5.0},
            {"unit": "1 tbsp", "weight_g": 14.0},
        ],
    },
    {
        "food_name": "Cheddar Cheese",
        "regional_name": "Cheese Slice",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("403.00"),
        "protein_per_100g": Decimal("24.90"),
        "carbs_per_100g": Decimal("1.30"),
        "fat_per_100g": Decimal("33.10"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("621.00"),
        "sugar_per_100g": Decimal("0.50"),
        "portion_sizes_json": [
            {"unit": "1 slice", "weight_g": 28.0},
        ],
    },
    {
        "food_name": "Salted Table Butter",
        "regional_name": "Makhan",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("733.00"),
        "protein_per_100g": Decimal("0.80"),
        "carbs_per_100g": Decimal("0.10"),
        "fat_per_100g": Decimal("81.10"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("580.00"),
        "sugar_per_100g": Decimal("0.10"),
        "portion_sizes_json": [
            {"unit": "1 cube", "weight_g": 10.0},
            {"unit": "1 tbsp", "weight_g": 14.0},
        ],
    },
    {
        "food_name": "Skimmed Milk",
        "regional_name": "Toned / Skimmed Milk",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("35.00"),
        "protein_per_100g": Decimal("3.40"),
        "carbs_per_100g": Decimal("4.90"),
        "fat_per_100g": Decimal("0.20"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("52.00"),
        "sugar_per_100g": Decimal("4.90"),
        "portion_sizes_json": [
            {"unit": "1 glass", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Unsweetened Soy Milk",
        "regional_name": "Soy Doodh",
        "category": "dairy_alternatives",
        "calories_per_100g": Decimal("43.00"),
        "protein_per_100g": Decimal("3.80"),
        "carbs_per_100g": Decimal("2.10"),
        "fat_per_100g": Decimal("2.00"),
        "fiber_per_100g": Decimal("1.00"),
        "sodium_per_100g": Decimal("45.00"),
        "sugar_per_100g": Decimal("0.80"),
        "portion_sizes_json": [
            {"unit": "1 glass", "weight_g": 200.0},
        ],
    },

    # 4. Poultry, Seafood, Eggs & Meats (12 items)
    {
        "food_name": "Whole Boiled Egg",
        "regional_name": "Ubla Anda",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("143.00"),
        "protein_per_100g": Decimal("12.60"),
        "carbs_per_100g": Decimal("0.70"),
        "fat_per_100g": Decimal("9.50"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("124.00"),
        "sugar_per_100g": Decimal("0.70"),
        "portion_sizes_json": [
            {"unit": "1 large egg", "weight_g": 50.0},
            {"unit": "2 large eggs", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Boiled Egg White",
        "regional_name": "Ande ki Safedi",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("52.00"),
        "protein_per_100g": Decimal("10.90"),
        "carbs_per_100g": Decimal("0.70"),
        "fat_per_100g": Decimal("0.20"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("166.00"),
        "sugar_per_100g": Decimal("0.70"),
        "portion_sizes_json": [
            {"unit": "2 egg whites", "weight_g": 66.0},
        ],
    },
    {
        "food_name": "Egg Omelet (Plain 2 eggs)",
        "regional_name": "Anda Omelette",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("154.00"),
        "protein_per_100g": Decimal("11.00"),
        "carbs_per_100g": Decimal("1.20"),
        "fat_per_100g": Decimal("11.50"),
        "fiber_per_100g": Decimal("0.10"),
        "sodium_per_100g": Decimal("240.00"),
        "sugar_per_100g": Decimal("0.80"),
        "portion_sizes_json": [
            {"unit": "1 serving", "weight_g": 110.0},
        ],
    },
    {
        "food_name": "Chicken Breast (Skinless Boiled/Grilled)",
        "regional_name": "Murg Breast",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("165.00"),
        "protein_per_100g": Decimal("31.00"),
        "carbs_per_100g": Decimal("0.00"),
        "fat_per_100g": Decimal("3.60"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("74.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "1 breast fillet", "weight_g": 150.0},
            {"unit": "100g serving", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Chicken Thigh (Cooked Boneless)",
        "regional_name": "Murg Thigh",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("209.00"),
        "protein_per_100g": Decimal("26.00"),
        "carbs_per_100g": Decimal("0.00"),
        "fat_per_100g": Decimal("10.90"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("86.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "1 thigh piece", "weight_g": 120.0},
        ],
    },
    {
        "food_name": "Tandoori Grilled Chicken",
        "regional_name": "Tandoori Chicken",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("185.00"),
        "protein_per_100g": Decimal("27.50"),
        "carbs_per_100g": Decimal("2.20"),
        "fat_per_100g": Decimal("7.10"),
        "fiber_per_100g": Decimal("0.40"),
        "sodium_per_100g": Decimal("340.00"),
        "sugar_per_100g": Decimal("0.50"),
        "portion_sizes_json": [
            {"unit": "1 leg/chest piece", "weight_g": 140.0},
        ],
    },
    {
        "food_name": "Rohu / Indian Carp Fish Curry",
        "regional_name": "Machhli Curry",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("145.00"),
        "protein_per_100g": Decimal("16.00"),
        "carbs_per_100g": Decimal("3.50"),
        "fat_per_100g": Decimal("7.20"),
        "fiber_per_100g": Decimal("0.80"),
        "sodium_per_100g": Decimal("280.00"),
        "sugar_per_100g": Decimal("0.50"),
        "portion_sizes_json": [
            {"unit": "1 piece with gravy", "weight_g": 160.0},
        ],
    },
    {
        "food_name": "Salmon Fillet (Pan Seared)",
        "regional_name": "Salmon Machhli",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("206.00"),
        "protein_per_100g": Decimal("22.10"),
        "carbs_per_100g": Decimal("0.00"),
        "fat_per_100g": Decimal("12.30"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("60.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "1 fillet", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Boiled Prawns / Shrimp",
        "regional_name": "Jhinga",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("99.00"),
        "protein_per_100g": Decimal("24.00"),
        "carbs_per_100g": Decimal("0.20"),
        "fat_per_100g": Decimal("0.30"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("111.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "10 medium prawns", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Mutton Curry (Goat Meat)",
        "regional_name": "Gosht / Mutton Curry",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("215.00"),
        "protein_per_100g": Decimal("18.50"),
        "carbs_per_100g": Decimal("3.00"),
        "fat_per_100g": Decimal("14.00"),
        "fiber_per_100g": Decimal("0.70"),
        "sodium_per_100g": Decimal("310.00"),
        "sugar_per_100g": Decimal("0.60"),
        "portion_sizes_json": [
            {"unit": "1 serving", "weight_g": 180.0},
        ],
    },
    {
        "food_name": "Canned Tuna in Water",
        "regional_name": "Tuna Fish",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("116.00"),
        "protein_per_100g": Decimal("26.00"),
        "carbs_per_100g": Decimal("0.00"),
        "fat_per_100g": Decimal("1.00"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("330.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "1 can drained", "weight_g": 120.0},
        ],
    },
    {
        "food_name": "Turkey Breast (Roast)",
        "regional_name": "Turkey Breast",
        "category": "poultry_seafood_meat",
        "calories_per_100g": Decimal("135.00"),
        "protein_per_100g": Decimal("30.00"),
        "carbs_per_100g": Decimal("0.00"),
        "fat_per_100g": Decimal("1.00"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("68.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "100g serving", "weight_g": 100.0},
        ],
    },

    # 5. Cooked Sabzis & Traditional Dishes (14 items)
    {
        "food_name": "Aloo Gobi",
        "regional_name": "Aloo Gobi Sabzi",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("115.00"),
        "protein_per_100g": Decimal("2.60"),
        "carbs_per_100g": Decimal("14.50"),
        "fat_per_100g": Decimal("5.20"),
        "fiber_per_100g": Decimal("3.20"),
        "sodium_per_100g": Decimal("260.00"),
        "sugar_per_100g": Decimal("2.20"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Palak Paneer",
        "regional_name": "Palak Paneer",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("165.00"),
        "protein_per_100g": Decimal("8.50"),
        "carbs_per_100g": Decimal("6.00"),
        "fat_per_100g": Decimal("12.00"),
        "fiber_per_100g": Decimal("2.80"),
        "sodium_per_100g": Decimal("290.00"),
        "sugar_per_100g": Decimal("1.50"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 160.0},
        ],
    },
    {
        "food_name": "Bhindi Masala (Okra)",
        "regional_name": "Bhindi ki Sabzi",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("98.00"),
        "protein_per_100g": Decimal("2.10"),
        "carbs_per_100g": Decimal("9.50"),
        "fat_per_100g": Decimal("5.80"),
        "fiber_per_100g": Decimal("3.50"),
        "sodium_per_100g": Decimal("240.00"),
        "sugar_per_100g": Decimal("2.00"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 140.0},
        ],
    },
    {
        "food_name": "Mixed Vegetable Sabzi",
        "regional_name": "Mix Veg",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("92.00"),
        "protein_per_100g": Decimal("2.40"),
        "carbs_per_100g": Decimal("11.00"),
        "fat_per_100g": Decimal("4.20"),
        "fiber_per_100g": Decimal("3.40"),
        "sodium_per_100g": Decimal("230.00"),
        "sugar_per_100g": Decimal("2.50"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Baingan Bharta (Roasted Eggplant)",
        "regional_name": "Baingan Bharta",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("88.00"),
        "protein_per_100g": Decimal("1.80"),
        "carbs_per_100g": Decimal("8.50"),
        "fat_per_100g": Decimal("5.20"),
        "fiber_per_100g": Decimal("3.00"),
        "sodium_per_100g": Decimal("220.00"),
        "sugar_per_100g": Decimal("3.20"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Matar Mushroom",
        "regional_name": "Khumb Matar",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("102.00"),
        "protein_per_100g": Decimal("4.50"),
        "carbs_per_100g": Decimal("9.80"),
        "fat_per_100g": Decimal("5.00"),
        "fiber_per_100g": Decimal("3.00"),
        "sodium_per_100g": Decimal("250.00"),
        "sugar_per_100g": Decimal("2.80"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Methi Malai Matar",
        "regional_name": "Methi Matar Malai",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("155.00"),
        "protein_per_100g": Decimal("4.20"),
        "carbs_per_100g": Decimal("12.00"),
        "fat_per_100g": Decimal("10.00"),
        "fiber_per_100g": Decimal("3.20"),
        "sodium_per_100g": Decimal("270.00"),
        "sugar_per_100g": Decimal("3.50"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Lauki Sabzi (Bottle Gourd)",
        "regional_name": "Ghia / Doodhi Sabzi",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("65.00"),
        "protein_per_100g": Decimal("1.20"),
        "carbs_per_100g": Decimal("6.00"),
        "fat_per_100g": Decimal("4.00"),
        "fiber_per_100g": Decimal("1.80"),
        "sodium_per_100g": Decimal("210.00"),
        "sugar_per_100g": Decimal("2.00"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Aloo Jeera",
        "regional_name": "Jeera Aloo",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("135.00"),
        "protein_per_100g": Decimal("2.00"),
        "carbs_per_100g": Decimal("19.00"),
        "fat_per_100g": Decimal("5.80"),
        "fiber_per_100g": Decimal("2.20"),
        "sodium_per_100g": Decimal("270.00"),
        "sugar_per_100g": Decimal("1.00"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 150.0},
        ],
    },
    {
        "food_name": "Paneer Bhurji",
        "regional_name": "Spiced Scrambled Paneer",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("195.00"),
        "protein_per_100g": Decimal("13.00"),
        "carbs_per_100g": Decimal("4.50"),
        "fat_per_100g": Decimal("13.80"),
        "fiber_per_100g": Decimal("1.50"),
        "sodium_per_100g": Decimal("280.00"),
        "sugar_per_100g": Decimal("1.80"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 140.0},
        ],
    },
    {
        "food_name": "Chicken Biryani (Home Style)",
        "regional_name": "Murgh Biryani",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("178.00"),
        "protein_per_100g": Decimal("9.50"),
        "carbs_per_100g": Decimal("21.00"),
        "fat_per_100g": Decimal("6.20"),
        "fiber_per_100g": Decimal("1.40"),
        "sodium_per_100g": Decimal("320.00"),
        "sugar_per_100g": Decimal("0.80"),
        "portion_sizes_json": [
            {"unit": "1 plate", "weight_g": 250.0},
        ],
    },
    {
        "food_name": "Vegetable Pulao",
        "regional_name": "Veg Pulao",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("145.00"),
        "protein_per_100g": Decimal("3.20"),
        "carbs_per_100g": Decimal("24.50"),
        "fat_per_100g": Decimal("3.80"),
        "fiber_per_100g": Decimal("2.20"),
        "sodium_per_100g": Decimal("260.00"),
        "sugar_per_100g": Decimal("1.20"),
        "portion_sizes_json": [
            {"unit": "1 plate", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Egg Bhurji (Scrambled Spiced Egg)",
        "regional_name": "Anda Bhurji",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("162.00"),
        "protein_per_100g": Decimal("11.50"),
        "carbs_per_100g": Decimal("2.80"),
        "fat_per_100g": Decimal("11.40"),
        "fiber_per_100g": Decimal("0.80"),
        "sodium_per_100g": Decimal("270.00"),
        "sugar_per_100g": Decimal("1.20"),
        "portion_sizes_json": [
            {"unit": "1 serving", "weight_g": 130.0},
        ],
    },
    {
        "food_name": "Kadhi Pakora",
        "regional_name": "Besan Kadhi Pakora",
        "category": "cooked_vegetables_dishes",
        "calories_per_100g": Decimal("138.00"),
        "protein_per_100g": Decimal("4.50"),
        "carbs_per_100g": Decimal("13.00"),
        "fat_per_100g": Decimal("7.50"),
        "fiber_per_100g": Decimal("1.80"),
        "sodium_per_100g": Decimal("340.00"),
        "sugar_per_100g": Decimal("2.50"),
        "portion_sizes_json": [
            {"unit": "1 katori", "weight_g": 160.0},
        ],
    },

    # 6. Raw Vegetables & Salads (12 items)
    {
        "food_name": "Cucumber (Raw with Peel)",
        "regional_name": "Kheera",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("15.00"),
        "protein_per_100g": Decimal("0.70"),
        "carbs_per_100g": Decimal("3.60"),
        "fat_per_100g": Decimal("0.10"),
        "fiber_per_100g": Decimal("0.50"),
        "sodium_per_100g": Decimal("2.00"),
        "sugar_per_100g": Decimal("1.70"),
        "portion_sizes_json": [
            {"unit": "1 medium cucumber", "weight_g": 120.0},
        ],
    },
    {
        "food_name": "Vine Tomato (Raw)",
        "regional_name": "Tamatar",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("18.00"),
        "protein_per_100g": Decimal("0.90"),
        "carbs_per_100g": Decimal("3.90"),
        "fat_per_100g": Decimal("0.20"),
        "fiber_per_100g": Decimal("1.20"),
        "sodium_per_100g": Decimal("5.00"),
        "sugar_per_100g": Decimal("2.60"),
        "portion_sizes_json": [
            {"unit": "1 medium tomato", "weight_g": 110.0},
        ],
    },
    {
        "food_name": "Red Onion (Raw)",
        "regional_name": "Pyaz",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("40.00"),
        "protein_per_100g": Decimal("1.10"),
        "carbs_per_100g": Decimal("9.30"),
        "fat_per_100g": Decimal("0.10"),
        "fiber_per_100g": Decimal("1.70"),
        "sodium_per_100g": Decimal("4.00"),
        "sugar_per_100g": Decimal("4.20"),
        "portion_sizes_json": [
            {"unit": "1 small onion", "weight_g": 70.0},
        ],
    },
    {
        "food_name": "Fresh Spinach (Raw)",
        "regional_name": "Palak Patta",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("23.00"),
        "protein_per_100g": Decimal("2.90"),
        "carbs_per_100g": Decimal("3.60"),
        "fat_per_100g": Decimal("0.40"),
        "fiber_per_100g": Decimal("2.20"),
        "sodium_per_100g": Decimal("79.00"),
        "sugar_per_100g": Decimal("0.40"),
        "portion_sizes_json": [
            {"unit": "1 cup raw", "weight_g": 30.0},
        ],
    },
    {
        "food_name": "Broccoli (Raw Florets)",
        "regional_name": "Broccoli",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("34.00"),
        "protein_per_100g": Decimal("2.80"),
        "carbs_per_100g": Decimal("6.60"),
        "fat_per_100g": Decimal("0.40"),
        "fiber_per_100g": Decimal("2.60"),
        "sodium_per_100g": Decimal("33.00"),
        "sugar_per_100g": Decimal("1.70"),
        "portion_sizes_json": [
            {"unit": "1 cup florets", "weight_g": 91.0},
        ],
    },
    {
        "food_name": "Shredded Iceberg Lettuce",
        "regional_name": "Salad Patta",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("14.00"),
        "protein_per_100g": Decimal("0.90"),
        "carbs_per_100g": Decimal("3.00"),
        "fat_per_100g": Decimal("0.10"),
        "fiber_per_100g": Decimal("1.20"),
        "sodium_per_100g": Decimal("10.00"),
        "sugar_per_100g": Decimal("2.00"),
        "portion_sizes_json": [
            {"unit": "1 cup", "weight_g": 72.0},
        ],
    },
    {
        "food_name": "Raw Carrot",
        "regional_name": "Gajar",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("41.00"),
        "protein_per_100g": Decimal("0.90"),
        "carbs_per_100g": Decimal("9.60"),
        "fat_per_100g": Decimal("0.20"),
        "fiber_per_100g": Decimal("2.80"),
        "sodium_per_100g": Decimal("69.00"),
        "sugar_per_100g": Decimal("4.70"),
        "portion_sizes_json": [
            {"unit": "1 medium carrot", "weight_g": 61.0},
        ],
    },
    {
        "food_name": "Raw Beetroot",
        "regional_name": "Chukandar",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("43.00"),
        "protein_per_100g": Decimal("1.60"),
        "carbs_per_100g": Decimal("9.60"),
        "fat_per_100g": Decimal("0.20"),
        "fiber_per_100g": Decimal("2.80"),
        "sodium_per_100g": Decimal("78.00"),
        "sugar_per_100g": Decimal("6.80"),
        "portion_sizes_json": [
            {"unit": "1 small beetroot", "weight_g": 80.0},
        ],
    },
    {
        "food_name": "Green Bell Pepper / Capsicum",
        "regional_name": "Shimla Mirch",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("20.00"),
        "protein_per_100g": Decimal("0.90"),
        "carbs_per_100g": Decimal("4.60"),
        "fat_per_100g": Decimal("0.20"),
        "fiber_per_100g": Decimal("1.70"),
        "sodium_per_100g": Decimal("3.00"),
        "sugar_per_100g": Decimal("2.40"),
        "portion_sizes_json": [
            {"unit": "1 medium capsicum", "weight_g": 120.0},
        ],
    },
    {
        "food_name": "Green Cabbage (Raw Shredded)",
        "regional_name": "Patta Gobi",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("25.00"),
        "protein_per_100g": Decimal("1.30"),
        "carbs_per_100g": Decimal("5.80"),
        "fat_per_100g": Decimal("0.10"),
        "fiber_per_100g": Decimal("2.50"),
        "sodium_per_100g": Decimal("18.00"),
        "sugar_per_100g": Decimal("3.20"),
        "portion_sizes_json": [
            {"unit": "1 cup", "weight_g": 89.0},
        ],
    },
    {
        "food_name": "White Radish / Mooli",
        "regional_name": "Mooli",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("16.00"),
        "protein_per_100g": Decimal("0.70"),
        "carbs_per_100g": Decimal("3.40"),
        "fat_per_100g": Decimal("0.10"),
        "fiber_per_100g": Decimal("1.60"),
        "sodium_per_100g": Decimal("39.00"),
        "sugar_per_100g": Decimal("1.90"),
        "portion_sizes_json": [
            {"unit": "1 radish", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Raw Cauliflower Florets",
        "regional_name": "Phool Gobi",
        "category": "raw_vegetables_salads",
        "calories_per_100g": Decimal("25.00"),
        "protein_per_100g": Decimal("1.90"),
        "carbs_per_100g": Decimal("5.00"),
        "fat_per_100g": Decimal("0.30"),
        "fiber_per_100g": Decimal("2.00"),
        "sodium_per_100g": Decimal("30.00"),
        "sugar_per_100g": Decimal("1.90"),
        "portion_sizes_json": [
            {"unit": "1 cup", "weight_g": 100.0},
        ],
    },

    # 7. Fresh Fruits (12 items)
    {
        "food_name": "Cavendish Banana",
        "regional_name": "Kela",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("89.00"),
        "protein_per_100g": Decimal("1.10"),
        "carbs_per_100g": Decimal("22.80"),
        "fat_per_100g": Decimal("0.30"),
        "fiber_per_100g": Decimal("2.60"),
        "sodium_per_100g": Decimal("1.00"),
        "sugar_per_100g": Decimal("12.20"),
        "portion_sizes_json": [
            {"unit": "1 medium banana", "weight_g": 118.0},
        ],
    },
    {
        "food_name": "Royal Gala Apple (with Skin)",
        "regional_name": "Seb",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("52.00"),
        "protein_per_100g": Decimal("0.30"),
        "carbs_per_100g": Decimal("13.80"),
        "fat_per_100g": Decimal("0.20"),
        "fiber_per_100g": Decimal("2.40"),
        "sodium_per_100g": Decimal("1.00"),
        "sugar_per_100g": Decimal("10.40"),
        "portion_sizes_json": [
            {"unit": "1 medium apple", "weight_g": 182.0},
        ],
    },
    {
        "food_name": "Fresh Papaya",
        "regional_name": "Papita",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("43.00"),
        "protein_per_100g": Decimal("0.50"),
        "carbs_per_100g": Decimal("10.80"),
        "fat_per_100g": Decimal("0.30"),
        "fiber_per_100g": Decimal("1.70"),
        "sodium_per_100g": Decimal("8.00"),
        "sugar_per_100g": Decimal("7.80"),
        "portion_sizes_json": [
            {"unit": "1 cup diced", "weight_g": 145.0},
        ],
    },
    {
        "food_name": "Fresh Guava",
        "regional_name": "Amrood",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("68.00"),
        "protein_per_100g": Decimal("2.60"),
        "carbs_per_100g": Decimal("14.30"),
        "fat_per_100g": Decimal("1.00"),
        "fiber_per_100g": Decimal("5.40"),
        "sodium_per_100g": Decimal("2.00"),
        "sugar_per_100g": Decimal("8.90"),
        "portion_sizes_json": [
            {"unit": "1 medium guava", "weight_g": 100.0},
        ],
    },
    {
        "food_name": "Alphonso Mango",
        "regional_name": "Aam",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("60.00"),
        "protein_per_100g": Decimal("0.80"),
        "carbs_per_100g": Decimal("15.00"),
        "fat_per_100g": Decimal("0.40"),
        "fiber_per_100g": Decimal("1.60"),
        "sodium_per_100g": Decimal("1.00"),
        "sugar_per_100g": Decimal("13.70"),
        "portion_sizes_json": [
            {"unit": "1 cup sliced", "weight_g": 165.0},
        ],
    },
    {
        "food_name": "Sweet Orange",
        "regional_name": "Santra / Mosambi",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("47.00"),
        "protein_per_100g": Decimal("0.90"),
        "carbs_per_100g": Decimal("11.80"),
        "fat_per_100g": Decimal("0.10"),
        "fiber_per_100g": Decimal("2.40"),
        "sodium_per_100g": Decimal("0.00"),
        "sugar_per_100g": Decimal("9.40"),
        "portion_sizes_json": [
            {"unit": "1 medium orange", "weight_g": 131.0},
        ],
    },
    {
        "food_name": "Fresh Watermelon",
        "regional_name": "Tarbooj",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("30.00"),
        "protein_per_100g": Decimal("0.60"),
        "carbs_per_100g": Decimal("7.60"),
        "fat_per_100g": Decimal("0.20"),
        "fiber_per_100g": Decimal("0.40"),
        "sodium_per_100g": Decimal("1.00"),
        "sugar_per_100g": Decimal("6.20"),
        "portion_sizes_json": [
            {"unit": "1 bowl diced", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Pomegranate Seeds",
        "regional_name": "Anaar Daana",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("83.00"),
        "protein_per_100g": Decimal("1.70"),
        "carbs_per_100g": Decimal("18.70"),
        "fat_per_100g": Decimal("1.20"),
        "fiber_per_100g": Decimal("4.00"),
        "sodium_per_100g": Decimal("3.00"),
        "sugar_per_100g": Decimal("13.70"),
        "portion_sizes_json": [
            {"unit": "1/2 cup", "weight_g": 87.0},
        ],
    },
    {
        "food_name": "Green Grapes",
        "regional_name": "Angoor",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("69.00"),
        "protein_per_100g": Decimal("0.70"),
        "carbs_per_100g": Decimal("18.10"),
        "fat_per_100g": Decimal("0.20"),
        "fiber_per_100g": Decimal("0.90"),
        "sodium_per_100g": Decimal("2.00"),
        "sugar_per_100g": Decimal("15.50"),
        "portion_sizes_json": [
            {"unit": "1 cup", "weight_g": 151.0},
        ],
    },
    {
        "food_name": "Fresh Pineapple",
        "regional_name": "Ananas",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("50.00"),
        "protein_per_100g": Decimal("0.50"),
        "carbs_per_100g": Decimal("13.10"),
        "fat_per_100g": Decimal("0.10"),
        "fiber_per_100g": Decimal("1.40"),
        "sodium_per_100g": Decimal("1.00"),
        "sugar_per_100g": Decimal("9.90"),
        "portion_sizes_json": [
            {"unit": "1 cup chunks", "weight_g": 165.0},
        ],
    },
    {
        "food_name": "Green Kiwi Fruit",
        "regional_name": "Kiwi",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("61.00"),
        "protein_per_100g": Decimal("1.10"),
        "carbs_per_100g": Decimal("14.70"),
        "fat_per_100g": Decimal("0.50"),
        "fiber_per_100g": Decimal("3.00"),
        "sodium_per_100g": Decimal("3.00"),
        "sugar_per_100g": Decimal("9.00"),
        "portion_sizes_json": [
            {"unit": "1 medium kiwi", "weight_g": 69.0},
        ],
    },
    {
        "food_name": "Mixed Berries (Strawberries & Blueberries)",
        "regional_name": "Berries",
        "category": "fresh_fruits",
        "calories_per_100g": Decimal("45.00"),
        "protein_per_100g": Decimal("0.80"),
        "carbs_per_100g": Decimal("11.00"),
        "fat_per_100g": Decimal("0.40"),
        "fiber_per_100g": Decimal("2.80"),
        "sodium_per_100g": Decimal("1.00"),
        "sugar_per_100g": Decimal("6.50"),
        "portion_sizes_json": [
            {"unit": "1 cup", "weight_g": 140.0},
        ],
    },

    # 8. Nuts, Seeds & Healthy Fats (8 items)
    {
        "food_name": "Raw Almonds",
        "regional_name": "Badam",
        "category": "nuts_seeds_fats",
        "calories_per_100g": Decimal("579.00"),
        "protein_per_100g": Decimal("21.20"),
        "carbs_per_100g": Decimal("21.60"),
        "fat_per_100g": Decimal("49.90"),
        "fiber_per_100g": Decimal("12.50"),
        "sodium_per_100g": Decimal("1.00"),
        "sugar_per_100g": Decimal("4.40"),
        "portion_sizes_json": [
            {"unit": "10 almonds", "weight_g": 12.0},
            {"unit": "1 handful", "weight_g": 28.0},
        ],
    },
    {
        "food_name": "Raw Walnuts",
        "regional_name": "Akhrot",
        "category": "nuts_seeds_fats",
        "calories_per_100g": Decimal("654.00"),
        "protein_per_100g": Decimal("15.20"),
        "carbs_per_100g": Decimal("13.70"),
        "fat_per_100g": Decimal("65.20"),
        "fiber_per_100g": Decimal("6.70"),
        "sodium_per_100g": Decimal("2.00"),
        "sugar_per_100g": Decimal("2.60"),
        "portion_sizes_json": [
            {"unit": "4 halves", "weight_g": 14.0},
            {"unit": "1 handful", "weight_g": 28.0},
        ],
    },
    {
        "food_name": "Chia Seeds",
        "regional_name": "Chia Beej",
        "category": "nuts_seeds_fats",
        "calories_per_100g": Decimal("486.00"),
        "protein_per_100g": Decimal("16.50"),
        "carbs_per_100g": Decimal("42.10"),
        "fat_per_100g": Decimal("30.70"),
        "fiber_per_100g": Decimal("34.40"),
        "sodium_per_100g": Decimal("16.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "1 tbsp", "weight_g": 12.0},
        ],
    },
    {
        "food_name": "Flax Seeds (Ground)",
        "regional_name": "Alsi Beej",
        "category": "nuts_seeds_fats",
        "calories_per_100g": Decimal("534.00"),
        "protein_per_100g": Decimal("18.30"),
        "carbs_per_100g": Decimal("28.90"),
        "fat_per_100g": Decimal("42.20"),
        "fiber_per_100g": Decimal("27.30"),
        "sodium_per_100g": Decimal("30.00"),
        "sugar_per_100g": Decimal("1.60"),
        "portion_sizes_json": [
            {"unit": "1 tbsp", "weight_g": 10.0},
        ],
    },
    {
        "food_name": "Roasted Peanuts (Unsalted)",
        "regional_name": "Moongphali",
        "category": "nuts_seeds_fats",
        "calories_per_100g": Decimal("585.00"),
        "protein_per_100g": Decimal("24.40"),
        "carbs_per_100g": Decimal("21.50"),
        "fat_per_100g": Decimal("49.70"),
        "fiber_per_100g": Decimal("8.00"),
        "sodium_per_100g": Decimal("6.00"),
        "sugar_per_100g": Decimal("4.20"),
        "portion_sizes_json": [
            {"unit": "1 handful", "weight_g": 30.0},
        ],
    },
    {
        "food_name": "Cashew Nuts (Raw)",
        "regional_name": "Kaju",
        "category": "nuts_seeds_fats",
        "calories_per_100g": Decimal("553.00"),
        "protein_per_100g": Decimal("18.20"),
        "carbs_per_100g": Decimal("30.20"),
        "fat_per_100g": Decimal("43.80"),
        "fiber_per_100g": Decimal("3.30"),
        "sodium_per_100g": Decimal("12.00"),
        "sugar_per_100g": Decimal("5.90"),
        "portion_sizes_json": [
            {"unit": "10 cashews", "weight_g": 15.0},
        ],
    },
    {
        "food_name": "Pumpkin Seeds",
        "regional_name": "Kaddu ke Beej",
        "category": "nuts_seeds_fats",
        "calories_per_100g": Decimal("559.00"),
        "protein_per_100g": Decimal("30.20"),
        "carbs_per_100g": Decimal("10.70"),
        "fat_per_100g": Decimal("49.00"),
        "fiber_per_100g": Decimal("6.00"),
        "sodium_per_100g": Decimal("7.00"),
        "sugar_per_100g": Decimal("1.40"),
        "portion_sizes_json": [
            {"unit": "1 tbsp", "weight_g": 15.0},
        ],
    },
    {
        "food_name": "Extra Virgin Olive Oil",
        "regional_name": "Jaitun ka Tel",
        "category": "nuts_seeds_fats",
        "calories_per_100g": Decimal("884.00"),
        "protein_per_100g": Decimal("0.00"),
        "carbs_per_100g": Decimal("0.00"),
        "fat_per_100g": Decimal("98.00"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("2.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "1 tsp", "weight_g": 5.0},
            {"unit": "1 tbsp", "weight_g": 14.0},
        ],
    },

    # 9. Healthy Snacks, Beverages & Supplements (8 items)
    {
        "food_name": "Roasted Chana (Bengal Gram)",
        "regional_name": "Bhuna Chana",
        "category": "snacks_beverages",
        "calories_per_100g": Decimal("369.00"),
        "protein_per_100g": Decimal("18.60"),
        "carbs_per_100g": Decimal("58.00"),
        "fat_per_100g": Decimal("5.20"),
        "fiber_per_100g": Decimal("16.80"),
        "sodium_per_100g": Decimal("28.00"),
        "sugar_per_100g": Decimal("3.00"),
        "portion_sizes_json": [
            {"unit": "1 handful", "weight_g": 30.0},
            {"unit": "1 bowl", "weight_g": 50.0},
        ],
    },
    {
        "food_name": "Roasted Makhana (Foxnuts Plain)",
        "regional_name": "Makhana",
        "category": "snacks_beverages",
        "calories_per_100g": Decimal("347.00"),
        "protein_per_100g": Decimal("9.70"),
        "carbs_per_100g": Decimal("76.90"),
        "fat_per_100g": Decimal("0.10"),
        "fiber_per_100g": Decimal("14.50"),
        "sodium_per_100g": Decimal("5.00"),
        "sugar_per_100g": Decimal("0.50"),
        "portion_sizes_json": [
            {"unit": "1 large bowl", "weight_g": 30.0},
        ],
    },
    {
        "food_name": "Tender Coconut Water",
        "regional_name": "Nariyal Paani",
        "category": "snacks_beverages",
        "calories_per_100g": Decimal("19.00"),
        "protein_per_100g": Decimal("0.70"),
        "carbs_per_100g": Decimal("3.70"),
        "fat_per_100g": Decimal("0.20"),
        "fiber_per_100g": Decimal("1.10"),
        "sodium_per_100g": Decimal("105.00"),
        "sugar_per_100g": Decimal("2.60"),
        "portion_sizes_json": [
            {"unit": "1 coconut", "weight_g": 240.0},
        ],
    },
    {
        "food_name": "Pure Green Tea (Brewed Unsweetened)",
        "regional_name": "Green Tea",
        "category": "snacks_beverages",
        "calories_per_100g": Decimal("1.00"),
        "protein_per_100g": Decimal("0.20"),
        "carbs_per_100g": Decimal("0.00"),
        "fat_per_100g": Decimal("0.00"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("1.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "1 cup", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Black Coffee (Brewed Unsweetened)",
        "regional_name": "Black Coffee",
        "category": "snacks_beverages",
        "calories_per_100g": Decimal("2.00"),
        "protein_per_100g": Decimal("0.30"),
        "carbs_per_100g": Decimal("0.20"),
        "fat_per_100g": Decimal("0.00"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("2.00"),
        "sugar_per_100g": Decimal("0.00"),
        "portion_sizes_json": [
            {"unit": "1 cup", "weight_g": 200.0},
        ],
    },
    {
        "food_name": "Vegetable Samosa (Fried)",
        "regional_name": "Samosa",
        "category": "snacks_beverages",
        "calories_per_100g": Decimal("262.00"),
        "protein_per_100g": Decimal("4.00"),
        "carbs_per_100g": Decimal("32.00"),
        "fat_per_100g": Decimal("13.00"),
        "fiber_per_100g": Decimal("2.80"),
        "sodium_per_100g": Decimal("390.00"),
        "sugar_per_100g": Decimal("1.80"),
        "portion_sizes_json": [
            {"unit": "1 samosa", "weight_g": 80.0},
        ],
    },
    {
        "food_name": "Besan Cheela (Gram Flour Pancake)",
        "regional_name": "Besan Puda / Cheela",
        "category": "snacks_beverages",
        "calories_per_100g": Decimal("185.00"),
        "protein_per_100g": Decimal("8.50"),
        "carbs_per_100g": Decimal("24.00"),
        "fat_per_100g": Decimal("6.00"),
        "fiber_per_100g": Decimal("4.20"),
        "sodium_per_100g": Decimal("260.00"),
        "sugar_per_100g": Decimal("1.50"),
        "portion_sizes_json": [
            {"unit": "1 medium cheela", "weight_g": 80.0},
        ],
    },
    {
        "food_name": "Whey Protein Isolate (Unflavored Powder)",
        "regional_name": "Whey Isolate",
        "category": "snacks_beverages",
        "calories_per_100g": Decimal("370.00"),
        "protein_per_100g": Decimal("88.00"),
        "carbs_per_100g": Decimal("2.50"),
        "fat_per_100g": Decimal("1.00"),
        "fiber_per_100g": Decimal("0.00"),
        "sodium_per_100g": Decimal("170.00"),
        "sugar_per_100g": Decimal("1.00"),
        "portion_sizes_json": [
            {"unit": "1 scoop", "weight_g": 30.0},
        ],
    },
]


async def seed_verified_foods(session: AsyncSession) -> int:
    """
    Asynchronously seeds FOOD_SEED_ITEMS into the database if not already present.
    Returns the count of seeded items.
    """
    inserted_count = 0
    for item in FOOD_SEED_ITEMS:
        result = await session.execute(
            select(VerifiedFoodReference).where(VerifiedFoodReference.food_name == item["food_name"])
        )
        existing = result.scalar_one_or_none()
        if existing is None:
            food = VerifiedFoodReference(
                id=uuid.uuid4(),
                food_name=item["food_name"],
                regional_name=item.get("regional_name"),
                category=item["category"],
                calories_per_100g=item["calories_per_100g"],
                protein_per_100g=item["protein_per_100g"],
                carbs_per_100g=item["carbs_per_100g"],
                fat_per_100g=item["fat_per_100g"],
                fiber_per_100g=item.get("fiber_per_100g", Decimal("0.00")),
                sodium_per_100g=item.get("sodium_per_100g", Decimal("0.00")),
                sugar_per_100g=item.get("sugar_per_100g", Decimal("0.00")),
                portion_sizes_json=item["portion_sizes_json"],
                is_verified=True,
            )
            session.add(food)
            inserted_count += 1
    await session.commit()
    return inserted_count


def generate_sql_seed_file(output_path: str = "backend/scripts/seed_food_reference.sql") -> None:
    """
    Generates an idempotent SQL seed file for PostgreSQL/Supabase.
    """
    lines = [
        "-- Seed Data: Verified Food Reference (105 Items)",
        "-- Compatible with PostgreSQL 16 / Supabase",
        "-- Idempotent insert with ON CONFLICT (food_name) DO NOTHING;",
        "",
    ]
    for item in FOOD_SEED_ITEMS:
        reg_name = f"'{item['regional_name']}'" if item.get("regional_name") else "NULL"
        portion_json_str = json.dumps(item["portion_sizes_json"]).replace("'", "''")
        food_name_escaped = item["food_name"].replace("'", "''")
        sql = (
            f"INSERT INTO verified_food_reference (\n"
            f"    id, food_name, regional_name, category, calories_per_100g, protein_per_100g,\n"
            f"    carbs_per_100g, fat_per_100g, fiber_per_100g, sodium_per_100g, sugar_per_100g,\n"
            f"    portion_sizes_json, is_verified, created_at\n"
            f") VALUES (\n"
            f"    gen_random_uuid(), '{food_name_escaped}', {reg_name}, '{item['category']}',\n"
            f"    {item['calories_per_100g']}, {item['protein_per_100g']}, {item['carbs_per_100g']},\n"
            f"    {item['fat_per_100g']}, {item['fiber_per_100g']}, {item['sodium_per_100g']},\n"
            f"    {item['sugar_per_100g']}, '{portion_json_str}'::jsonb, TRUE, CURRENT_TIMESTAMP\n"
            f") ON CONFLICT (food_name) DO NOTHING;\n"
        )
        lines.append(sql)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    generate_sql_seed_file()
    print(f"Generated SQL seed file with {len(FOOD_SEED_ITEMS)} verified foods.")
